\connect enfase

insert into question (_text, answer) values ('foo?', 2);
insert into choice (question_id, index, _text) values (1, 0, 'foo');
insert into choice (question_id, index, _text) values (1, 1, 'bar');
insert into choice (question_id, index, _text) values (1, 2, 'baz');
insert into choice (question_id, index, _text) values (1, 3, 'qux');
insert into choice (question_id, index, _text) values (1, 4, 'quux');
